name: Test Client

run-name: ${{ github.actor }} is testing > ${{ github.event.head_commit.message }}

on: push

jobs:
  Testing:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20'

      - name: Installing
        run: cd client && yarn
          
        
      - name: Testing
        run: cd client && yarn test
    